apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-demo
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-demo
  template:
    metadata:
      labels:
        app: rollout-demo
    spec:
      containers:
      - name: rollout-demo
        image: nginx:1.26.0
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 100
